name: tcc_neto_garage
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  shared_preferences: ^2.5.2
  http: ^0.13.6
  table_calendar: ^3.2.0
  intl: ^0.20.2
  camera: ^0.11.1
  image: ^4.5.3
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.0.2
  fl_chart: ^0.71.0
  iconify_flutter: ^0.0.5
  
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/images/
    - assets/icons/
    - .env

  uses-material-design: true
  fonts:
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Italic.ttf
        - asset: assets/fonts/ABeeZee-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf