name: tcc_neto_garage
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  firebase_auth: ^5.4.2
  lottie: ^2.2.0
  animate_do: ^2.1.0
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  assets:

   - assets/images/
   - assets/img/

  uses-material-design: true

  fonts:
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Italic.ttf
        - asset: assets/fonts/ABeeZee-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
